### PR TITLE
Update action to node20

### PR DESCRIPTION
**Pull request by takost**
Node 16 has reached end-of-life on 11 Sep 202.
This PR updates the default runtime to node20, rather then node16.

This is supported on all Actions Runners [v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) or later.

### CODE REVIEW

**Review by camchenry — APPROVED** [review]

**Comment by takost** [comment]
@camchenry Could you please merge this PR and release new versions of the action? I don't have permissions for it 😄

**Comment by massongit** [comment]
https://github.com/dev-hato/actions-diff-pr-management/actions/runs/7687682574

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/add-to-project@v0.5.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

This warning appears when I run workflows used this Actions.
Therefore, please release this PR.

**Review by joshrowley — APPROVED** [review]
🚀🚢  Thank you for this @takost!

**Comment by MikeMcC399** [comment]
Hi @joshrowley 

Will there now be a new release which includes this commit for `node20` support? At the moment I only see it in the `main` branch.

**Pull request merged**
